version: "3"

services:
  nodejs:
    image: node:12
    working_dir: /app/api
    command: bash -c "chmod +x /app/api/start.sh && /bin/sh -c /app/api/start.sh"
    depends_on:
     - db
    volumes:
     - ./app/api:/app/api
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prootexample
      MYSQL_DATABASE: 3cxmon
      MYSQL_USER: uexample
      MYSQL_PASSWORD: pexample
    ports:
     - "3306:3306"
    volumes:
     - './database-service/db:/var/lib/mysql'
     - './database-service/dump:/docker-entrypoint-initdb.d'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - './grafana/env.grafana'
    user: "0"
    links:
      - db
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

